//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageTheMoney.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManageTheMoney.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   January;February;March;April;May;June;July;August;September;October;November;December benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CmbMonths {
            get {
                return ResourceManager.GetString("CmbMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CmbMonthsText {
            get {
                return ResourceManager.GetString("CmbMonthsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CmbYearsText {
            get {
                return ResourceManager.GetString("CmbYearsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Statement benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FrmMainContentText {
            get {
                return ResourceManager.GetString("FrmMainContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage The Money benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FrmMainText {
            get {
                return ResourceManager.GetString("FrmMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previus Statement benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GrpPreviousStatementText {
            get {
                return ResourceManager.GetString("GrpPreviousStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Statement benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GrpStatementText {
            get {
                return ResourceManager.GetString("GrpStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expenses : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LblExpensesText {
            get {
                return ResourceManager.GetString("LblExpensesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incomes : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LblIncomesText {
            get {
                return ResourceManager.GetString("LblIncomesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Expenses : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LblPreviousExpensesText {
            get {
                return ResourceManager.GetString("LblPreviousExpensesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Incomes : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LblPreviousIncomesText {
            get {
                return ResourceManager.GetString("LblPreviousIncomesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Total : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LblPreviousTotalText {
            get {
                return ResourceManager.GetString("LblPreviousTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LblTotalText {
            get {
                return ResourceManager.GetString("LblTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Menu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TsmiMainMenuText {
            get {
                return ResourceManager.GetString("TsmiMainMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenarios benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TsmiScenariosMenuText {
            get {
                return ResourceManager.GetString("TsmiScenariosMenuText", resourceCulture);
            }
        }
    }
}
