//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageTheMoney.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManageTheMoney.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Scenario benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BtnAddScenarioText {
            get {
                return ResourceManager.GetString("BtnAddScenarioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BtnCancelText {
            get {
                return ResourceManager.GetString("BtnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Scenario benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BtnDeleteScenarioText {
            get {
                return ResourceManager.GetString("BtnDeleteScenarioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Scenario benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BtnEditScenarioText {
            get {
                return ResourceManager.GetString("BtnEditScenarioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BtnLoginText {
            get {
                return ResourceManager.GetString("BtnLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BtnRegisterText {
            get {
                return ResourceManager.GetString("BtnRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   January;February;March;April;May;June;July;August;September;October;November;December benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CmbMonths {
            get {
                return ResourceManager.GetString("CmbMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CmbMonthsText {
            get {
                return ResourceManager.GetString("CmbMonthsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CmbYearsText {
            get {
                return ResourceManager.GetString("CmbYearsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username or password is incorrect! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ErrorLoginFailedMessage {
            get {
                return ResourceManager.GetString("ErrorLoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register Failed! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ErrorRegisterFailedMessage {
            get {
                return ResourceManager.GetString("ErrorRegisterFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FrmLoginText {
            get {
                return ResourceManager.GetString("FrmLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Statement benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FrmMainContentText {
            get {
                return ResourceManager.GetString("FrmMainContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage The Money benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FrmMainText {
            get {
                return ResourceManager.GetString("FrmMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FrmRegisterText {
            get {
                return ResourceManager.GetString("FrmRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenarios benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FrmScenariosText {
            get {
                return ResourceManager.GetString("FrmScenariosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GrpEditScenariosText {
            get {
                return ResourceManager.GetString("GrpEditScenariosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GrpLoginText {
            get {
                return ResourceManager.GetString("GrpLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previus Statement benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GrpPreviousStatementText {
            get {
                return ResourceManager.GetString("GrpPreviousStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GrpRegisterText {
            get {
                return ResourceManager.GetString("GrpRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenarios Table benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GrpScenariosTable {
            get {
                return ResourceManager.GetString("GrpScenariosTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Statement benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GrpStatementText {
            get {
                return ResourceManager.GetString("GrpStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date of Birth benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblDateOfBirthText {
            get {
                return ResourceManager.GetString("LblDateOfBirthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expenses : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblExpensesText {
            get {
                return ResourceManager.GetString("LblExpensesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incomes : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblIncomesText {
            get {
                return ResourceManager.GetString("LblIncomesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblMailText {
            get {
                return ResourceManager.GetString("LblMailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblNameText {
            get {
                return ResourceManager.GetString("LblNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblPasswordText {
            get {
                return ResourceManager.GetString("LblPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone Number : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblPhoneNumberText {
            get {
                return ResourceManager.GetString("LblPhoneNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Expenses : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblPreviousExpensesText {
            get {
                return ResourceManager.GetString("LblPreviousExpensesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Incomes : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblPreviousIncomesText {
            get {
                return ResourceManager.GetString("LblPreviousIncomesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Total : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblPreviousTotalText {
            get {
                return ResourceManager.GetString("LblPreviousTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surname : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblSurnameText {
            get {
                return ResourceManager.GetString("LblSurnameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblTotalText {
            get {
                return ResourceManager.GetString("LblTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LblUsernameText {
            get {
                return ResourceManager.GetString("LblUsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amount benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleAmount {
            get {
                return ResourceManager.GetString("ScenarioGridTitleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created At benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleCreatedAt {
            get {
                return ResourceManager.GetString("ScenarioGridTitleCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currency benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleCurrency {
            get {
                return ResourceManager.GetString("ScenarioGridTitleCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleDescription {
            get {
                return ResourceManager.GetString("ScenarioGridTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected Date benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleExpectedDate {
            get {
                return ResourceManager.GetString("ScenarioGridTitleExpectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected Date End benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleExpectedDateEnd {
            get {
                return ResourceManager.GetString("ScenarioGridTitleExpectedDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IsNecessery benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleIsNecessary {
            get {
                return ResourceManager.GetString("ScenarioGridTitleIsNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is Realized benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleIsRealized {
            get {
                return ResourceManager.GetString("ScenarioGridTitleIsRealized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Probability benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleProbability {
            get {
                return ResourceManager.GetString("ScenarioGridTitleProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realized At benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleRealizedAt {
            get {
                return ResourceManager.GetString("ScenarioGridTitleRealizedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recurring benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleRecurring {
            get {
                return ResourceManager.GetString("ScenarioGridTitleRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleTitle {
            get {
                return ResourceManager.GetString("ScenarioGridTitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenario Type benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleType {
            get {
                return ResourceManager.GetString("ScenarioGridTitleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updated At benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScenarioGridTitleUpdatedAt {
            get {
                return ResourceManager.GetString("ScenarioGridTitleUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Menu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TsmiMainMenuText {
            get {
                return ResourceManager.GetString("TsmiMainMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenarios benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TsmiScenariosMenuText {
            get {
                return ResourceManager.GetString("TsmiScenariosMenuText", resourceCulture);
            }
        }
    }
}
